volumes:
  cs2s-client:  # Persist our download
    name: cs2s-client
    external: true
services:
  cs2s:
    build: .  # Use ./Dockerfile
    tty: true  # Allows us to attach
    cap_add:
      - SYS_ADMIN  # Allows us to mount overlays
    environment:
      # Timezone for CLI
      - TZ=${TZ-America/New_York}  # Allow empty TZ
    ports:
      - ${PORT:-27015}:27015/tcp
      - ${PORT:-27015}:27015/udp
      - ${TV_PORT:-27020}:27020/udp
      - ${CLIENT_PORT:-27005}:27005/udp
      - ${STEAM_PORT:-26900}:26900/udp
    volumes:
      - ${WORK:-.}:/work  # Mount the current working directory
      - type: volume  # Persist the downloaded client
        source: cs2s-client
        target: /cs2/
